---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: github-listener-route
spec:
  to:
    kind: Service
    name: el-github-listener
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
